# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import parameter_server_pb2 as parameter__server__pb2


class ParameterServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UpdateGradients = channel.unary_unary(
        '/ParameterServer/UpdateGradients',
        request_serializer=parameter__server__pb2.GradientUpdate.SerializeToString,
        response_deserializer=parameter__server__pb2.GradientUpdateResponse.FromString,
        )
    self.GetModel = channel.unary_unary(
        '/ParameterServer/GetModel',
        request_serializer=parameter__server__pb2.ModelRequest.SerializeToString,
        response_deserializer=parameter__server__pb2.Model.FromString,
        )


class ParameterServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UpdateGradients(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ParameterServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UpdateGradients': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateGradients,
          request_deserializer=parameter__server__pb2.GradientUpdate.FromString,
          response_serializer=parameter__server__pb2.GradientUpdateResponse.SerializeToString,
      ),
      'GetModel': grpc.unary_unary_rpc_method_handler(
          servicer.GetModel,
          request_deserializer=parameter__server__pb2.ModelRequest.FromString,
          response_serializer=parameter__server__pb2.Model.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ParameterServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
