# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameter_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parameter_server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16parameter_server.proto\"(\n\x08Gradient\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c\".\n\x0eGradientUpdate\x12\x1c\n\tgradients\x18\x01 \x03(\x0b\x32\t.Gradient\"\x18\n\x16GradientUpdateResponse\"&\n\x06Weight\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c\"!\n\x05Model\x12\x18\n\x07weights\x18\x01 \x03(\x0b\x32\x07.Weight\"\x0e\n\x0cModelRequest2u\n\x0fParameterServer\x12=\n\x0fUpdateGradients\x12\x0f.GradientUpdate\x1a\x17.GradientUpdateResponse\"\x00\x12#\n\x08GetModel\x12\r.ModelRequest\x1a\x06.Model\"\x00\x62\x06proto3')
)




_GRADIENT = _descriptor.Descriptor(
  name='Gradient',
  full_name='Gradient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Gradient.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Gradient.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=66,
)


_GRADIENTUPDATE = _descriptor.Descriptor(
  name='GradientUpdate',
  full_name='GradientUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gradients', full_name='GradientUpdate.gradients', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=114,
)


_GRADIENTUPDATERESPONSE = _descriptor.Descriptor(
  name='GradientUpdateResponse',
  full_name='GradientUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=140,
)


_WEIGHT = _descriptor.Descriptor(
  name='Weight',
  full_name='Weight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Weight.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Weight.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=180,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='weights', full_name='Model.weights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=215,
)


_MODELREQUEST = _descriptor.Descriptor(
  name='ModelRequest',
  full_name='ModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=231,
)

_GRADIENTUPDATE.fields_by_name['gradients'].message_type = _GRADIENT
_MODEL.fields_by_name['weights'].message_type = _WEIGHT
DESCRIPTOR.message_types_by_name['Gradient'] = _GRADIENT
DESCRIPTOR.message_types_by_name['GradientUpdate'] = _GRADIENTUPDATE
DESCRIPTOR.message_types_by_name['GradientUpdateResponse'] = _GRADIENTUPDATERESPONSE
DESCRIPTOR.message_types_by_name['Weight'] = _WEIGHT
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['ModelRequest'] = _MODELREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gradient = _reflection.GeneratedProtocolMessageType('Gradient', (_message.Message,), {
  'DESCRIPTOR' : _GRADIENT,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:Gradient)
  })
_sym_db.RegisterMessage(Gradient)

GradientUpdate = _reflection.GeneratedProtocolMessageType('GradientUpdate', (_message.Message,), {
  'DESCRIPTOR' : _GRADIENTUPDATE,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:GradientUpdate)
  })
_sym_db.RegisterMessage(GradientUpdate)

GradientUpdateResponse = _reflection.GeneratedProtocolMessageType('GradientUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRADIENTUPDATERESPONSE,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:GradientUpdateResponse)
  })
_sym_db.RegisterMessage(GradientUpdateResponse)

Weight = _reflection.GeneratedProtocolMessageType('Weight', (_message.Message,), {
  'DESCRIPTOR' : _WEIGHT,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:Weight)
  })
_sym_db.RegisterMessage(Weight)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:Model)
  })
_sym_db.RegisterMessage(Model)

ModelRequest = _reflection.GeneratedProtocolMessageType('ModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELREQUEST,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:ModelRequest)
  })
_sym_db.RegisterMessage(ModelRequest)



_PARAMETERSERVER = _descriptor.ServiceDescriptor(
  name='ParameterServer',
  full_name='ParameterServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=233,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateGradients',
    full_name='ParameterServer.UpdateGradients',
    index=0,
    containing_service=None,
    input_type=_GRADIENTUPDATE,
    output_type=_GRADIENTUPDATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetModel',
    full_name='ParameterServer.GetModel',
    index=1,
    containing_service=None,
    input_type=_MODELREQUEST,
    output_type=_MODEL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARAMETERSERVER)

DESCRIPTOR.services_by_name['ParameterServer'] = _PARAMETERSERVER

# @@protoc_insertion_point(module_scope)
